CXXFLAGS  += -I__BASE__/include -I__BASE__/include/star -DHAVE_CONFIG_H
CFLAGS    +=	-O -Wconversion # -Werror=conversion
CXXFLAGS  +=	-O -Wconversion # -Werror=conversion



CXXFLAGS += -D_SRC_='"no_source_available"'
